import { describe, expect, it } from "vitest";
import type { Plan } from "./plan.js";
import { renderJson, renderPretty, renderRoadmapMarkdown } from "./render.js";

function plan(overrides: Partial<Plan> = {}): Plan {
  return { backlog: [], sprints: [], ...overrides };
}

describe("renderJson", () => {
  it("returns the plan data itself, structured", () => {
    const p = plan({
      backlog: [
        {
          id: 1,
          title: "Dark mode",
          status: "idea",
          sprint: "",
          createdAt: "",
          updatedAt: "",
          hasSpec: false,
          hasLog: false,
        },
      ],
    });
    expect(JSON.parse(renderJson(p))).toEqual(p);
  });
});

describe("renderPretty", () => {
  it("shows BACKLOG with a count and each issue", () => {
    const p = plan({
      backlog: [
        {
          id: 12,
          title: "Rework auth",
          status: "ready",
          sprint: "",
          createdAt: "",
          updatedAt: "",
          hasSpec: true,
          hasLog: true,
        },
        {
          id: 15,
          title: "Dark mode",
          status: "idea",
          sprint: "",
          createdAt: "",
          updatedAt: "",
          hasSpec: false,
          hasLog: false,
        },
      ],
    });
    const out = renderPretty(p);
    expect(out).toContain("BACKLOG (2)");
    expect(out).toContain("#12");
    expect(out).toContain("ready");
    expect(out).toContain("Rework auth");
    expect(out).toContain("[spec]");
    expect(out).toContain("[log]");
    expect(out).toContain("#15");
    expect(out).toContain("Dark mode");
  });

  it("shows an empty backlog as BACKLOG (0) with no issue lines", () => {
    expect(renderPretty(plan())).toContain("BACKLOG (0)");
  });

  it("omits the backlog section entirely when filtered to a single sprint", () => {
    const out = renderPretty(plan({ filteredBySprint: "foundation" }));
    expect(out).not.toContain("BACKLOG");
  });

  it("marks the active sprint with a leading marker, others without", () => {
    const p = plan({
      sprints: [
        { name: "auth-hardening", position: 10, status: "active", goal: "g", notes: "", active: true, issues: [] },
        { name: "onboarding", position: 20, status: "planned", goal: "g2", notes: "", active: false, issues: [] },
      ],
    });
    const out = renderPretty(p);
    expect(out).toContain("▶ SPRINT auth-hardening");
    expect(out).toContain("(active)");
    expect(out).toContain("SPRINT onboarding");
    expect(out).toContain("(planned)");
    expect(out).not.toContain("▶ SPRINT onboarding");
  });

  it("shows each sprint's goal and its issues", () => {
    const p = plan({
      sprints: [
        {
          name: "foundation",
          position: 10,
          status: "planned",
          goal: "build the mechanical layer",
          notes: "",
          active: false,
          issues: [
            {
              id: 3,
              title: "Rotate signing keys",
              status: "doing",
              sprint: "foundation",
              createdAt: "",
              updatedAt: "",
              hasSpec: false,
              hasLog: false,
            },
          ],
        },
      ],
    });
    const out = renderPretty(p);
    expect(out).toContain("goal: build the mechanical layer");
    expect(out).toContain("#3");
    expect(out).toContain("doing");
    expect(out).toContain("Rotate signing keys");
  });
});

describe("renderRoadmapMarkdown", () => {
  it("starts with a generated-file header pointing back at the CLI", () => {
    const out = renderRoadmapMarkdown(plan());
    expect(out).toContain("# Roadmap");
    expect(out).toContain("Generated by scrummy");
    expect(out).toContain("scrummy");
  });

  it("renders backlog issues as a checklist, unchecked for non-done status", () => {
    const p = plan({
      backlog: [
        {
          id: 12,
          title: "Rework auth",
          status: "ready",
          sprint: "",
          createdAt: "",
          updatedAt: "",
          hasSpec: false,
          hasLog: false,
        },
      ],
    });
    const out = renderRoadmapMarkdown(p);
    expect(out).toContain("## Backlog");
    expect(out).toContain("- [ ] #12 Rework auth");
  });

  it("checks off done issues", () => {
    const p = plan({
      backlog: [
        {
          id: 1,
          title: "Ship it",
          status: "done",
          sprint: "",
          createdAt: "",
          updatedAt: "",
          hasSpec: false,
          hasLog: false,
        },
      ],
    });
    const out = renderRoadmapMarkdown(p);
    expect(out).toContain("- [x] #1 Ship it");
  });

  it("groups issues under a heading per sprint, with the goal and active marker", () => {
    const p = plan({
      sprints: [
        {
          name: "foundation",
          position: 10,
          status: "active",
          goal: "build the mechanical layer",
          notes: "",
          active: true,
          issues: [
            {
              id: 3,
              title: "Rotate signing keys",
              status: "doing",
              sprint: "foundation",
              createdAt: "",
              updatedAt: "",
              hasSpec: false,
              hasLog: false,
            },
          ],
        },
      ],
    });
    const out = renderRoadmapMarkdown(p);
    expect(out).toContain("## Sprint: foundation (active)");
    expect(out).toContain("build the mechanical layer");
    expect(out).toContain("- [ ] #3 Rotate signing keys");
  });

  it("omits the backlog heading entirely when there is no backlog", () => {
    const out = renderRoadmapMarkdown(plan());
    expect(out).not.toContain("## Backlog");
  });

  it("renders a sprint with no issues without crashing", () => {
    const p = plan({
      sprints: [
        {
          name: "empty-sprint",
          position: 1,
          status: "planned",
          goal: "",
          notes: "",
          active: false,
          issues: [],
        },
      ],
    });
    const out = renderRoadmapMarkdown(p);
    expect(out).toContain("## Sprint: empty-sprint (planned)");
  });

  it("checks off a done issue inside a sprint", () => {
    const p = plan({
      sprints: [
        {
          name: "foundation",
          position: 10,
          status: "done",
          goal: "",
          notes: "",
          active: false,
          issues: [
            {
              id: 7,
              title: "Done in sprint",
              status: "done",
              sprint: "foundation",
              createdAt: "",
              updatedAt: "",
              hasSpec: false,
              hasLog: false,
            },
          ],
        },
      ],
    });
    const out = renderRoadmapMarkdown(p);
    expect(out).toContain("- [x] #7 Done in sprint");
  });
});
